### ISSUE TITLE
Which version of entypo can be used?

### ISSUE THREAD

**Issue by YesThatAllen** [moderatorwes/Notification-Banner#2]
I noticed you linked back to an [old version of Enytpo](http://web.archive.org/web/20140912210715/http://entypo.com/characters/).  Do you know the most recent version we can use is?

**Comment by moderatorwes** [comment]
Zendesk uses the Entypo fonts so I have no idea what version they are using.  I pretty sure they are using an older version but you would have to contact Zendesk to get the exact version.

Hope this helps,
Wes
