### ISSUE TITLE
Latest "Guide" version of Zendesk

### ISSUE THREAD

**Issue by kMikaZu** [moderatorwes/Notification-Banner#5]
In the latest version of Zendesk (the "Guide"-version), the Notification bar disappears.

**Comment by moderatorwes** [comment]
Are you still seeing this issue as I'm not seeing on my end?

**Comment by kMikaZu** [comment]
Yes, I'm still experiencing this issue. Very strange.

**Comment by moderatorwes** [comment]
You must have some other code or modifications that are interfering as you can see it worked successfully for someone today who posted a comment. 
[https://support.zendesk.com/hc/en-us/community/posts/207738148-Adding-a-notification-banner-to-your-Help-Center-v2?page=4#community_comment_115004454928]

**Comment by kMikaZu** [comment]
Hi

I've found the culprit, some faulty close statements. 
Thanks!
